default_install_hook_types:
  - pre-commit
  - commit-msg
  - pre-push

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: check-merge-conflict
        stages: &precomm-stages [pre-commit, manual]
      - id: check-yaml
        stages: *precomm-stages
      - id: detect-private-key
        stages: *precomm-stages
      - id: mixed-line-ending
        stages: *precomm-stages

  - repo: https://github.com/FeryET/pre-commit-rust
    rev: 2b764ff13b37a64a57232a99363e6438e8877c5c  # frozen: v1.2.1
    hooks:
      - id: fmt
      - id: cargo-check
      - id: test
      - id: build

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: 91ab4bf57e58b32adf1a122681f6ebe164d081c8  # frozen: v4.4.0
    hooks:
      - id: conventional-pre-commit
        args: [--strict]
