default_install_hook_types:
  - pre-commit
  - commit-msg
  - pre-push

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
        stages: &precomm-stages [pre-commit, manual]
      - id: check-yaml
        stages: *precomm-stages
      - id: detect-private-key
        stages: *precomm-stages
      - id: mixed-line-ending
        stages: *precomm-stages

  - repo: https://github.com/FeryET/pre-commit-rust
    rev: v1.2.1
    hooks:
      - id: fmt
      - id: cargo-check
      - id: test
      - id: build

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.4.0
    hooks:
      - id: conventional-pre-commit
        args: [--strict]
