name: Translate Files

on:
  push:
    branches:
      - main

jobs:
  translate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # Fetch last 2 commits

      - name: Run Translation Action
        uses: Kolozuz/llm-translate-action@master
        with:
          api_key: ${{ secrets.API_KEY }}
          ai_service: "gemini"  # Options: openai, gemini, claude, azure
          ai_model: "gemini-3.1-flash-lite-preview"  # Specify model (e.g., gemini-pro, claude-v1)
          target_langs: "French, Japanese, Spanish"
          target_lang_codes: "fr, ja, es"
          file_exts: "md"
          output_format: "docs/*_{lang}.{ext}"
