name: Translate Files

on:
  push:
    branches:
      - main

jobs:
  translate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Translation Action
        uses: imaun/gpt-translate-action@v1.9.0
        with:
          api_key: ${{ secrets.API_KEY }}
          ai_service: "gemini"  # Options: openai, gemini, claude, azure
          ai_model: "gemini-3-flash-preview"      # Specify model (e.g., gemini-pro, claude-v1)
          target_lang: "Spanish"
          target_lang_code: "es"
          file_exts: "md"
          output_format: "translated_*.{ext}"
          base_branch: main # Default is GITHUB_BASE_REF from env
